version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
    groups:
      dev-dependencies:
        dependency-type: development
    labels:
      - dependencies

  - package-ecosystem: npm
    directory: /site
    schedule:
      interval: weekly
    groups:
      docs-dependencies:
        dependency-type: development
    labels:
      - dependencies
      - docs

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    labels:
      - dependencies
      - ci
